### ISSUE TITLE
Twitch error connection

### ISSUE THREAD

**Issue by lvlmd** [c0deum/BroChat#11]
![monosnap 2016-09-14 21-18-49](https://cloud.githubusercontent.com/assets/4421245/18535285/e80ce854-7ac0-11e6-82c6-fa1a99fdd24c.png)

**Comment by JAremko** [comment]
Кодиеум, хватить Сватов смотреть. Го фиксь :bm:

**Comment by Dunkon** [comment]
@c0deum имей совесть!

**Comment by c0deum** [comment]
fixed

**Comment by Ranzo** [comment]
вновь эта же ошибка, no fixed!!!
