### ISSUE TITLE
trying to make mac app via qtcreator

### ISSUE THREAD

**Issue by Chidorin** [c0deum/BroChat#15]
trying to make mac app via qtcreator got this error 

/brochat/qlivecodingchat.h:6: error: 'QXmppClient.h' file not found
#include <QXmppClient.h>

**Comment by c0deum** [comment]
add binary https://github.com/c0deum/BroChat/releases/download/BroChat20161116MSVC32.zip/BroChatMacOSX20161121Clang64.zip

**Comment by c0deum** [comment]
building steps:

clone brochat
go to brochat dir
git submodule init
git submodule update
go to external/qxmpp-master subdir
build qxmpp as static library: 
qmake QXMPP_LIBRARY_TYPE=staticlib
make
after that you can build brochat (._. )
