### ISSUE TITLE
News builds for MAC also

### ISSUE THREAD

**Issue by lvlmd** [c0deum/BroChat#19]
Please, add ready app for Mac users when you build a new one for Win.
Thanks, a lot!

**Comment by Ingerdev** [comment]
Редкий билд долетит до мак юзера

**Comment by Dunkon** [comment]
@Ingerdev главное как следует достать кое-кого ;) (@c0deum)

**Comment by c0deum** [comment]
Add new binary for Mac (._. )
https://github.com/c0deum/BroChat/releases/tag/BroChatMacOSX20161126Clang64
