### ISSUE TITLE
Не работает прокрутка чата

### ISSUE THREAD

**Issue by Ingerdev** [c0deum/BroChat#21]
В до-WebEngine версии прокрутка работает.

**Comment by Ingerdev** [comment]
Потестил у себя - прокрутка колесом работает. 
У пользователя не работает, вин 7.

**Comment by c0deum** [comment]
может работает не в ту сторону?
:peka:

**Comment by Ingerdev** [comment]
Это предположение не подтвердилось. Также, чатик был активным окном, проверялось множественным тыканием мышки.

**Comment by c0deum** [comment]
на всех темах?

**Comment by Ingerdev** [comment]
Детальное разбирательство установило, что не работала homm3 тема старой версии чата. Апдейт стилей решил проблему. Однако, прокрутка работает вверх ногами.
