### ISSUE TITLE
mac/linux

### ISSUE THREAD

**Issue by Chidorin** [c0deum/BroChat#7]
would be nice to see compiled versions for mac and linux or at least instructions how to make it

**Comment by whitesunset** [comment]
+1

**Comment by c0deum** [comment]
+1 https://funstream.tv/build/images/smiles/rnbw.png
- see build.sh on dev branch

**Comment by Chidorin** [comment]
Idk what to do with it https://funstream.tv/build/images/smiles/rnbw.png

**Comment by Chidorin** [comment]
after running this command in terminal I get "qmake-qt5: command not found"

**Comment by c0deum** [comment]
try qmake, on my system( Fedora ) i use qmake-qt5...
Requirements:
Qt 5.5+

**Comment by Chidorin** [comment]
qtkit 7.7.3,  same error "Submodule path 'external/qxmpp-master': checked out '90b681f47c7370d23bf7cd8cdda0fe41449cc255'
-bash: qmake: command not found"

**Comment by c0deum** [comment]
[Qt, not QT](https://www.qt.io/download-open-source/)

**Comment by Chidorin** [comment]
same error, how to check qt version and if path is written ok

**Comment by JAremko** [comment]
+1

**Comment by drewoko** [comment]
+1

**Comment by Chidorin** [comment]
tried to make it with qtcreator got this Info: creating stash file /Users/chidorin/build-BroChat-Desktop_Qt_5_7_0_clang_64bit-Debug/.qmake.stash
Project ERROR: Unknown module(s) in QT: webkitwidgets
18:22:09: Процесс «/Users/chidorin/Qt/5.7/clang_64/bin/qmake»

**Comment by c0deum** [comment]
ok, find some errors on pro file, release for mac:
https://github.com/c0deum/BroChat/releases/download/BroChat20160624MinGW32/BroChat20160630MacClang64.zip

**Comment by Chidorin** [comment]
thx Bro ![alt tag](https://camo.githubusercontent.com/c24b9320ab45325ae0c957e59b0c276fbe699795/68747470733a2f2f66756e73747265616d2e74762f6275696c642f696d616765732f736d696c65732f726e62772e706e67)
