### ISSUE TITLE
Последняя версия для Mac?

### ISSUE THREAD

**Issue by lvlmd** [c0deum/BroChat#9]
Как скачать и существует ли вообще версия для Mac ?
Спасибо

**Comment by c0deum** [comment]
[https://github.com/c0deum/BroChat/releases/download/BroChat20160624MinGW32/BroChat20160630MacClang64.zip](https://github.com/c0deum/BroChat/releases/download/BroChat20160624MinGW32/BroChat20160630MacClang64.zip) вроде бы оно

**Comment by lvlmd** [comment]
Спасибо! Теперь понятно где лежат релизы
